#!/bin/bash

PRJDIR="$(dirname $(realpath $0))/.."

[ -f ~/.tmux.conf ] && rm ~/.tmux.conf
[ -f ~/.tmux ] && rm ~/.tmux
[ ! -h ~/.tmux ] && [ -d ~/.tmux ] && mv ~/.tmux ~/tmux.old
[ -h ~/.tmux ] && rm ~/.tmux
ln -fs ${PRJDIR}/etc/tmux.conf ~/.tmux.conf
ln -fs ${PRJDIR}/etc/tmux ~/.tmux

[ -f ~/.bashrc ] && rm ~/.bashrc
ln -fs ${PRJDIR}/etc/bashrc ~/.bashrc

[ -f ~/.profile ] && rm ~/.profile
ln -fs ${PRJDIR}/etc/profile ~/.profile

[ ! -h ~/scripts ] && [ -d ~/scripts ] && mv ~/scripts ~/scripts.old
[ -h ~/scripts ] && rm ~/scripts
ln -fs ${PRJDIR}/scripts ~/scripts

[ ! -h ~/etc ] && [ -d ~/etc ] && mv ~/etc ~/etc.old
[ -h ~/etc ] && rm ~/etc
ln -fs ${PRJDIR}/etc ~/etc

